Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/01/2021
Var
 x, y , soma : real
 


Inicio
 escreval("digite aqui o valor de X ")
 leia(x)
 
 escreval("digite aqui o valor de  ")
 leia(y)
 
 soma <- x + y
 
 escreval(" A SOMA DE X e Y : " , soma)
 

Fimalgoritmo